name: Build

on:
  workflow_dispatch:
  push:
    branches:       
      - main             
  pull_request:
    branches: 
      - main
permissions:
  pull-requests: write
jobs:  
  build:
    env:
      TESTS_PROJECT: 'Tests/Tests.csproj' # path to test project or solution
      PUBLISH_NUGET: false # if true a nuget will be published on version change
      RUN_TESTS: true # if true tests are run and coverage data is published to coveralls and a coverage report is produced.
      MAIN_CSPROJ: 'TreeMeX/TreeMeX.csproj' # main project (for nuget packaging)
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Clean artifacts and nugets 
      run: dotnet clean  --configuration Release && dotnet nuget locals all --clear
    - name: Build with dotnet 
      run: dotnet build --configuration Release
    - name: Test with dotnet
      uses: b3b00/coverlet-action@1.2.4
      id: 'coverlet'
      if: env.RUN_TESTS
      with:
        testProject: ${{env.TESTS_PROJECT}}
        output: 'lcov.info'
        threshold: 30
        outputFormat: 'lcov'
        excludes: '[Tests]*'
    - name : deploy railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
    
